/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type SessionManagementSubscriptionData struct {
	SingleNssai *Snssai `json:"singleNssai" yaml:"singleNssai" bson:"singleNssai" mapstructure:"SingleNssai"`
	// A map (list of key-value pairs where Dnn serves as key) of DnnConfigurations
	DnnConfigurations          map[string]DnnConfiguration `json:"dnnConfigurations,omitempty" bson:"dnnConfigurations" mapstructure:"DnnConfigurations" yaml:"dnnConfigurations,omitempty"`
	InternalGroupIds           []string                    `json:"internalGroupIds,omitempty" yaml:"internalGroupIds,omitempty" bson:"internalGroupIds" mapstructure:"InternalGroupIds"`
	SharedDnnConfigurationsIds string                      `json:"sharedDnnConfigurationsIds,omitempty" yaml:"sharedDnnConfigurationsIds,omitempty" bson:"sharedDnnConfigurationsIds" mapstructure:"SharedDnnConfigurationsIds"`
}
