/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// Contains the SM policy data for a given DNN (and S-NSSAI).
type SmPolicyDnnData struct {
	Dnn                 string                            `json:"dnn" bson:"dnn" yaml:"dnn"`
	AllowedServices     []string                          `json:"allowedServices,omitempty" bson:"allowedServices" yaml:"allowedServices,omitempty"`
	SubscCats           []string                          `json:"subscCats,omitempty" bson:"subscCats" yaml:"subscCats,omitempty"`
	GbrUl               string                            `json:"gbrUl,omitempty" bson:"gbrUl" yaml:"gbrUl,omitempty"`
	GbrDl               string                            `json:"gbrDl,omitempty" bson:"gbrDl" yaml:"gbrDl,omitempty"`
	AdcSupport          bool                              `json:"adcSupport,omitempty" bson:"adcSupport" yaml:"adcSupport,omitempty"`
	SubscSpendingLimits bool                              `json:"subscSpendingLimits,omitempty" bson:"subscSpendingLimits" yaml:"subscSpendingLimits,omitempty"`
	Ipv4Index           int32                             `json:"ipv4Index,omitempty" bson:"ipv4Index" yaml:"ipv4Index,omitempty"`
	Ipv6Index           int32                             `json:"ipv6Index,omitempty" bson:"ipv6Index" yaml:"ipv6Index,omitempty"`
	Offline             bool                              `json:"offline,omitempty" bson:"offline" yaml:"offline,omitempty"`
	Online              bool                              `json:"online,omitempty" bson:"online" yaml:"online,omitempty"`
	ChfInfo             *ChargingInformation              `json:"chfInfo,omitempty" bson:"chfInfo" yaml:"chfInfo,omitempty"`
	RefUmDataLimitIds   map[string]LimitIdToMonitoringKey `json:"refUmDataLimitIds,omitempty" bson:"refUmDataLimitIds" yaml:"refUmDataLimitIds,omitempty"`
	MpsPriority         bool                              `json:"mpsPriority,omitempty" bson:"mpsPriority" yaml:"mpsPriority,omitempty"`
	ImsSignallingPrio   bool                              `json:"imsSignallingPrio,omitempty" bson:"imsSignallingPrio" yaml:"imsSignallingPrio,omitempty"`
	MpsPriorityLevel    int32                             `json:"mpsPriorityLevel,omitempty" bson:"mpsPriorityLevel" yaml:"mpsPriorityLevel,omitempty"`
}
