/*
 * Nudr_DataRepository API OpenAPI file
 *
 * Unified Data Repository Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Tuak struct {
	Top              *Top  `json:"top,omitempty" bson:"top" yaml:"top,omitempty"`
	KeccakIterations int32 `json:"keccakIterations,omitempty" bson:"keccakIterations" yaml:"keccakIterations,omitempty"`
}
